@startuml

autonumber

Invoker -> Signature: Request{clientId,clientSecret,pubKey,payload}
Signature -> Cipher: AESEnc(clientSecret,payload)
Signature <-- Cipher: encryptPayload
Signature -> Digest: HMAC(encryptPayload,clientSecret + pubKey)
Signature <-- Digest: digest
Signature -> Signature: sign = (RSAEnc(pubKey) + "." + digest)
Invoker <-- Signature: Response{encryptPayload,sign}

@enduml