@startuml

autonumber

Invoker -> RpcEncrypt: Request{clientId,encryptPayload,sign}
RpcEncrypt -> STORAGE: {clientId}
RpcEncrypt <-- STORAGE: {clientSecret,priKey,pubKey}
RpcEncrypt -> Signature: {clientId,clientSecret,priKey,pubKey,encryptPayload,sign}
Signature -> Digest: {encryptPayload,clientSecret + pubKey)
Signature <-- Digest: digest = HMAC(encryptPayload,clientSecret + pubKey)
Signature -> Signature: validate digest (sign part 2
Signature -> Asymmetric: {sign,priKey}
Signature <-- Asymmetric: aysDec = RSADec(sign part1, priKey)
Signature -> Signature: validate aysDec (sign part 1
Signature -> Symmetric: {clientSecret,payload}
Signature <-- Symmetric: payload = AESDec(clientSecret,payload)
RpcEncrypt <-- Signature: payload
Invoker <-- RpcEncrypt: Response{payload}

@enduml